server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false


spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    locale: es_MX
    resources:
      add-mappings: false

  profiles:
    active: ${profileActive}

  datasource:
    url: jdbc:postgresql://localhost:5432/LibraryBD
    username: postgres
    password: 1234

    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 120000

  jta:
    enabled: true




